name: test
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn compile
    - run: yarn package
    - run: yarn test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up HLint
      uses: rwe/actions-hlint-setup@v1

    - run: hlint --version

    - uses: ./
      with:
        path: test/Example.hs
