name: "/hlint-run"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

defaults:
  run:
    working-directory: "./hlint-run"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn compile
    - run: yarn package
    - run: yarn test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up HLint
      #  2021-11-12: NOTE: Currently uses old pulished location, until `haslell/actions/hlint-setup` works properly
      uses: rwe/actions-hlint-setup@v1

    - run: hlint --version

    #  2021-11-12: NOTE: Is this would be relative to the default workdir?
    - uses: ./
      with:
        path: test/Example.hs
