name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # only run on "releases" (pushes to tags)
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
    - run: git show HEAD --format='%s%n%n%b' -s > .release_body
    - uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        body_path: .release_body
